channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - pip=23.0.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==24.1.2 # https://rpaframework.org/releasenotes.html
      - pandas==2.0.1
      - gevent==22.10.2
      - XlsxWriter==3.1.2
      - pyxlsb
      